export const categoryEmojis: Record<string, string> = {
  'All': '🌟',
  'Communication': '💬',
  'Artificial Intelligence (AI)': '🤖',
  'Social Media': '📱',
  'CRM': '👥',
  'Marketing': '📈',
  'Analytics': '📊',
  'Commerce': '📊',
  'Databases': '🗄️',
  'File Storage': '🗂️',
  'Help Desk & Support': '🎧',
  'Infrastructure & Cloud': '🌐',
  'E-commerce': '🛒',
  'Developer Tools': '🔧',
  'Web & App Development': '🌐',
  'Business Management': '💼',
  'Productivity': '⚡',
  'Finance': '💰',
  'Email': '📧',
  'Project Management': '📋',
  'Storage': '💾',
  'AI/ML': '🤖',
  'Data & Databases': '🗄️',
  'Video': '🎥',
  'Calendar': '📅',
  'Forms': '📝',
  'Security': '🔒',
  'HR': '👔',
  'Sales': '💼',
  'Support': '🎧',
  'Design': '🎨',
  'Business Intelligence': '📈',
  'Automation': '🔄',
  'News': '📰',
  'Weather': '🌤️',
  'Travel': '✈️',
  'Education': '🎓',
  'Health': '🏥',
};

export const PAGINATION_CONSTANTS = {
  FIRST_PAGE: 'FIRST_PAGE',
  POPULAR_APPS_COUNT: 6,
} as const; 