MODEL_ACCESS_TIERS = {
    "free": [
        "openrouter/deepseek/deepseek-chat",
        "openrouter/qwen/qwen3-235b-a22b",
    ],
    "tier_2_20": [
        "openrouter/deepseek/deepseek-chat",
        # "xai/grok-3-mini-fast-beta",
        "openai/gpt-4o",
        # "openai/gpt-4-turbo",
        # "xai/grok-3-fast-latest",
        # "openrouter/google/gemini-2.5-flash-preview",
        # "openai/gpt-4",
        "anthropic/claude-3-7-sonnet-latest",
        # "openai/gpt-4.1-2025-04-14",
        # "openrouter/deepseek/deepseek-r1",
        "openrouter/qwen/qwen3-235b-a22b",
    ],
    "tier_6_50": [
        "openrouter/deepseek/deepseek-chat",
        # "xai/grok-3-mini-fast-beta",
        "openai/gpt-4o",
        # "openai/gpt-4-turbo",
        # "xai/grok-3-fast-latest",
        # "openrouter/google/gemini-2.5-flash-preview",
        # "openai/gpt-4",
        "anthropic/claude-3-7-sonnet-latest",
        # "openai/gpt-4.1-2025-04-14",
        # "openrouter/deepseek/deepseek-r1",
        "openrouter/qwen/qwen3-235b-a22b",
    ],
    "tier_12_100": [
        "openrouter/deepseek/deepseek-chat",
        # "xai/grok-3-mini-fast-beta",
        "openai/gpt-4o",
        # "openai/gpt-4-turbo",
        # "xai/grok-3-fast-latest",
        # "openrouter/google/gemini-2.5-flash-preview",
        # "openai/gpt-4",
        "anthropic/claude-3-7-sonnet-latest",
        # "openai/gpt-4.1-2025-04-14",
        # "openrouter/deepseek/deepseek-r1",
        "openrouter/qwen/qwen3-235b-a22b",
    ],
    "tier_25_200": [
        "openrouter/deepseek/deepseek-chat",
        # "xai/grok-3-mini-fast-beta",
        "openai/gpt-4o",
        # "openai/gpt-4-turbo",
        # "xai/grok-3-fast-latest",
        # "openrouter/google/gemini-2.5-flash-preview",
        # "openai/gpt-4",
        "anthropic/claude-3-7-sonnet-latest",
        # "openai/gpt-4.1-2025-04-14",
        # "openrouter/deepseek/deepseek-r1",
        "openrouter/qwen/qwen3-235b-a22b",
    ],
    "tier_50_400": [
        "openrouter/deepseek/deepseek-chat",
        # "xai/grok-3-mini-fast-beta",
        "openai/gpt-4o",
        # "openai/gpt-4-turbo",
        # "xai/grok-3-fast-latest",
        # "openrouter/google/gemini-2.5-flash-preview",
        # "openai/gpt-4",
        "anthropic/claude-3-7-sonnet-latest",
        # "openai/gpt-4.1-2025-04-14",
        # "openrouter/deepseek/deepseek-r1",
        "openrouter/qwen/qwen3-235b-a22b",
    ],
    "tier_125_800": [
        "openrouter/deepseek/deepseek-chat",
        # "xai/grok-3-mini-fast-beta",
        "openai/gpt-4o",
        # "openai/gpt-4-turbo",
        # "xai/grok-3-fast-latest",
        # "openrouter/google/gemini-2.5-flash-preview",
        # "openai/gpt-4",
        "anthropic/claude-3-7-sonnet-latest",
        # "openai/gpt-4.1-2025-04-14",
        # "openrouter/deepseek/deepseek-r1",
        "openrouter/qwen/qwen3-235b-a22b",
    ],
    "tier_200_1000": [
        "openrouter/deepseek/deepseek-chat",
        # "xai/grok-3-mini-fast-beta",
        "openai/gpt-4o",
        # "openai/gpt-4-turbo",
        # "xai/grok-3-fast-latest",
        # "openrouter/google/gemini-2.5-flash-preview",
        # "openai/gpt-4",
        "anthropic/claude-3-7-sonnet-latest",
        # "openai/gpt-4.1-2025-04-14",
        # "openrouter/deepseek/deepseek-r1",
        "openrouter/qwen/qwen3-235b-a22b",
    ],
}
