export const categoryIcons = {
  "AI & Search": "🤖",
  "Development & Version Control": "🔧",
  "Automation & Productivity": "⚡",
  "Communication & Collaboration": "💬",
  "Project Management": "📅",
  "Data & Analytics": "📊",
  "Cloud & Infrastructure": "☁️",
  "File Storage": "📁",
  "Marketing & Sales": "🛒",
  "Customer Support": "🎧",
  "Finance": "💰",
  "Utilities": "🔨",
  "Other": "🧩",

  "development": "🔧",
  "ai": "🤖",
  "automation": "⚡",
  "search": "🔍",
  "Database": "📊",
  "Web": "🌐",
  "File": "📄",
  "Development": "💻",
  "AI": "🤖",
  "Cloud": "☁️",
  "Utility": "⚡",
  "Integration": "🧩",
};